/*
 *  @file  : ScdIcdCheckServiceTest.cpp
 *  @author: luteng
 *  @date  : 2015-07-01 16:50:06.835
 *  @note  : Generated by SlxTemplates
 */

#include "../gsoap/ScdIcdChecker.nsmap"
#include "../gsoap/soapScdIcdCheckerProxy.h"
#include "../ScdCheckCommon/charconv.h"
#include <stdio.h>
#pragma warning(disable: 4786)
#include <iostream>
#include <string>

using namespace std;

// test.exe endpoint configFilePath FilePath ResultStorePath
int main(int argc, char *argv[])
{
    setlocale(LC_ALL, "chs");
//     if (argc < 5)
//     {
//         cout<<"usage: test.exe endpoint configFilePath FilePath ResultStorePath"<<endl;
//         return 0;
//     }

    std::string strResultJson;
    ScdIcdCheckerProxy proxy("127.0.0.1:23389");

#if 1
    //int nResult = proxy.ScdCrcCalc(argv[2], argv[3], strResultJson);
    int nResult = proxy.ScdCheck(argv[2], argv[3], argv[4], strResultJson);
#else
    int nResult = proxy.IcdCheck(argv[2], argv[3], argv[4], strResultJson);
#endif

    cout<<"soap result: "<<nResult<<endl
        <<"service result: "<<strResultJson<<endl;

    return 0;
}