/*
 *  @file  : ScdIcdCheckService_ServiceTools.h
 *  @author: luteng
 *  @date  : 2015-08-28 16:33:28.452
 *  @note  : Generated by SlxTemplates
 */

#ifndef _SCDICDCHECKSERVICE_SERVICETOOLS_H
#define _SCDICDCHECKSERVICE_SERVICETOOLS_H

#include <Windows.h>

#define _SERVER_SERVICE_NAME            TEXT("ScdIcdCheckService")
#define _SERVER_SERVICE_DISPLAY_NAME    TEXT("ScdIcdCheckService display name")
#define _SERVER_SERVICE_DESCRIPTION     TEXT("ScdIcdCheckService description")
#define MSGBOXSLIENT                    0

namespace ScdIcdCheckService_ServiceTools {

int ToolMessageBoxFormat(HWND hWindow, LPCTSTR lpCaption, UINT uType, LPCTSTR pFmt, ...);
BOOL ToolInstallLocalServerService(HWND hWindow);
BOOL ToolUninstallLocalServerService(HWND hWindow);
BOOL ToolStartLocalServerService(HWND hWindow);
BOOL ToolStopLocalServerService(HWND hWindow);
BOOL ToolForkForElevat(LPCTSTR lpArgument);
BOOL ToolNeedToElevat();

}; // namespace ScdIcdCheckService_ServiceTools

#endif /* _SERVICETOOLS_H */