/*
 *  @file  : ScdIcdCheckService_ServiceWork.h
 *  @author: luteng
 *  @date  : 2015-07-01 16:50:06.835
 *  @note  : Generated by SlxTemplates
 */

#ifndef _SCDICDCHECKSERVICE_SERVICEWORK_H
#define _SCDICDCHECKSERVICE_SERVICEWORK_H

#ifdef __cplusplus
extern "C" {
#endif

#include <Windows.h>

// lpParam实为HANDLE hStopEvent
DWORD CALLBACK ScdIcdCheckServiceWorkProc(LPVOID lpParam);

#ifdef __cplusplus
}
#endif

#endif /* _SERVICEWORK_H */