/*
 *  @file  : ScdIcdCheckService_ServiceWork.cpp
 *  @author: luteng
 *  @date  : 2015-07-01 16:50:06.835
 *  @note  : Generated by SlxTemplates
 */

#include "ScdIcdCheckService_ServiceWork.h"
#include "ScdIcdCheckService_Config.h"
#include "ScdIcdCheckService_SoapServer.h"
#include "ScdIcdCheckService_CheckerInvoker.h"
#include "ScdIcdCheckService_ScdCalcCrcInvoker.h"
#include "../ScdCheckCommon/KillOnJobClose.h"
#include <Shlwapi.h>
#include <strsafe.h>

DWORD CALLBACK ScdIcdCheckServiceWorkProc(LPVOID lpParam)
{
    HANDLE hStopEvent = lpParam;
    WSADATA wd;

    WSAStartup(MAKEWORD(2, 2), &wd);

    SetKillOnJobClose();

    TCHAR szCurrentDirectory[MAX_PATH];

    GetModuleFileName(GetModuleHandle(NULL), szCurrentDirectory, RTL_NUMBER_OF(szCurrentDirectory));
    PathRemoveFileSpec(szCurrentDirectory);
    SetCurrentDirectory(szCurrentDirectory);

    if (!CScdIcdCheckService_Config::InitializeInstance())
    {
        SafeDebugMessageA("SclCompare2Service_Config初始化失败\r\n");
        return 0;
    }

    if (!CScdIcdCheckService_CheckerInvoker::InitializeInstance())
    {
        SafeDebugMessageA("CScdIcdCheckService_CheckerInvoker初始化失败\r\n");
        return 0;
    }

    if (!CScdIcdCheckService_ScdCalcCrcInvoker::InitializeInstance())
    {
        SafeDebugMessageA("CScdIcdCheckService_ScdCalcCrcInvoker初始化失败\r\n");
        return 0;
    }

    ScdIcdCheckService_SoapServer *pSoapServer = NULL;

    try
    {
        pSoapServer = new ScdIcdCheckService_SoapServer(
            CScdIcdCheckService_Config::GetInstance()->GetPortID(),
            CScdIcdCheckService_Config::GetInstance()->GetThreadCount());

        DWORD dwIndx = 0;
        while (WAIT_TIMEOUT == WaitForSingleObject(hStopEvent, 3030))
        {
            TCHAR szText[4096];

            StringCchPrintf(szText, RTL_NUMBER_OF(szText), TEXT("eaServer running, %lu\r\n"), dwIndx++);

            if (dwIndx % 10 == 0)
            {
                OutputDebugString(szText);
            }
        }
    }
    catch (std::exception &ex)
    {
        SafeDebugMessageA("ScdIcdCheckServiceWorkProc异常%hs", ex.what());
    }

    if (pSoapServer != NULL)
    {
        delete pSoapServer;
    }

    return 0;
}