/*
 *  @file  : ScdIcdCheckService_ServiceMain.h
 *  @author: luteng
 *  @date  : 2015-07-01 16:50:06.835
 *  @note  : Generated by SlxTemplates
 */

#ifndef _SCDICDCHECKSERVICE_SERVICEMAIN_H
#define _SCDICDCHECKSERVICE_SERVICEMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <Windows.h>

VOID WINAPI ScdIcdCheckService_ServiceMainProc(DWORD dwArgc, LPTSTR *lpszArgv);

#ifdef __cplusplus
}
#endif

#endif /* _SERVICEMAIN_H */