/*
 *  @file  : ScdCrcCalculator.h
 *  @author: luteng
 *  @date  : 2015-07-14 15:16:11.343
 *  @note  : Generated by SlxTemplates
 */

#ifndef _SCDCRCCALCULATOR_H
#define _SCDCRCCALCULATOR_H

#include <Windows.h>

#ifdef _MSC_VER
    #ifdef SCDCRCCALCULATOR_EXPORTS
        #define SCDCRCCALCULATOR_API __declspec(dllexport)
    #else
        #define SCDCRCCALCULATOR_API __declspec(dllimport)
    #endif
#else
    #define SCDCRCCALCULATOR_API
#endif

// 传入文件路径、错误代码缓冲区，返回结果xml
// 全部采用utf8编码
LPCSTR WINAPI CalcCrc(LPCSTR lpFilePath, char szErrorMessage[], int nBufferSize);

// 释放CalcCrc返回的缓冲区
void WINAPI CalcCrcFreeMemory(LPCSTR lpText);

#endif /* _SCDCRCCALCULATOR_H */
