//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ScdIcdCheckTool.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SCLHEAT_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDB_TITLE_SCL                   131
#define IDD_DLG_ANALYZE                 135
#define IDD_DLG_CRC                     138
#define IDD_DIALOG_ATTRIBUTE            141
#define IDD_DIALOG_SCD_OR_ICD           143
#define IDD_DIALOG_CONFIG_LIST          144
#define IDB_FOLDERS                     144
#define IDB_FOLDER                      144
#define IDD_DIALOG_ICD_INPUT            145
#define IDR_ICDCRCCALCTOOL              147
#define IDR_ICON_UCENTER                150
#define IDR_ICON_BAOHU                  151
#define IDR_BACK_DESKTOP                152
#define IDR_BACK_SCAN                   153
#define IDR_BACK_UCENTER                155
#define IDR_BACK_BAOHU                  156
#define IDR_BTN_CLOSE                   157
#define IDR_BTN_MINIMIZE                158
#define IDR_BACK_FREE                   160
#define IDR_ARROW                       161
#define IDR_FRAME                       162
#define IDR_HOVER                       164
#define IDR_BTN_GREEN                   165
#define IDR_ICON_DESKTOP                167
#define IDR_ICON_SCAN                   168
#define IDD_CONFIG_SAVE_DIALOG          171
#define IDD_DIALOG_SAVEAS_CONFIG        172
#define IDC_BTN_ICDVALID                1000
#define IDC_EDIT_ICDPATH                1008
#define IDC_BTN_CHECK                   1010
#define IDC_LIST_REPORT                 1011
#define IDC_BTN_SCLCOMPARE              1013
#define IDC_STATIC_NEWBUSY              1013
#define IDC_STATIC_TITLE                1014
#define IDC_BTN_ICDSCD                  1015
#define IDC_BTN_CIDSCD                  1016
#define IDC_BTN_                        1017
#define IDC_BTN_CHECK_SAVE              1017
#define IDC                             1018
#define IDC_BTN_CHECK_SAVE2             1019
#define IDC_BUTTON_SELECT               1037
#define IDC_BUTTON_CEXPORT_DOC          1038
#define IDC_LIST2                       1039
#define IDC_STATIC_BASICINFO            1040
#define IDC_STATIC_FILENAME             1042
#define IDC_STATIC_FILEPATH             1043
#define IDC_STATIC_FILENAME2            1044
#define IDC_STATIC_DATE                 1044
#define IDC_STATIC_FILENAME3            1045
#define IDC_STATIC_TIME                 1045
#define IDC_STATIC_FILENAME4            1046
#define IDC_STATIC_SCDCRC               1046
#define IDC_STATIC_FILENAME5            1047
#define IDC_STATIC_CRCCOUNT             1047
#define IDC_CHECK_WARRN                 1051
#define IDC_CHECK6                      1057
#define IDC_EDIT1                       1072
#define IDC_EDIT                        1072
#define IDC_EDIT_CFG_FILE               1072
#define IDC_EDIT_MSG                    1072
#define IDC_EDIT_NEWNAME                1072
#define IDC_EDIT_SAVEAS_NAME            1072
#define IDC_EDIT_CONTENT2               1073
#define IDC_EDIT_ICD_FILE               1073
#define IDC_EDIT_POSITION               1073
#define IDC_COMBO_ICD_TYPE              1074
#define IDC_EDIT_CLASS                  1074
#define IDC_BUTTON_BROWSER_CFG          1075
#define IDC_EDIT_XML                    1075
#define IDC_BUTTON_BROWSER_ICD          1076
#define IDC_EDIT_DESC                   1076
#define IDC_BUTTON_CONFIG               1076
#define IDC_BUTTON_CHECK                1077
#define IDC_EDIT_REFERENCE              1077
#define IDC_BUTTON_EXPORT_EXCEL         1078
#define IDC_LIST                        1080
#define IDC_COMBO_MSG                   1081
#define IDC_COMBO_CHECKITEM             1082
#define IDC_CHECK1                      1085
#define IDC_CHECK_SHOWLAST              1085
#define IDC_BUTTON_BROWSER              1087
#define IDC_EDIT_FILE                   1094
#define IDC_STATIC_SUMMER               1095
#define IDC_PROGRESS_EXPORT_EXCEL       1096
#define IDC_BUTTON_CANCEL_EXCEL         1097
#define IDC_COMBO_ICD_VOLTAGE           1099
#define IDC_EDIT2                       1099
#define IDC_BUTTON_ENABLE_ALL           1100
#define IDC_BUTTON2                     1101
#define IDC_BUTTON_DISENABLE_ALL        1101
#define IDC_COMBO1                      1101
#define IDC_COMBO_CFG_FILE              1101
#define IDC_LIST_CONFIG                 1103
#define IDC_BUTTON1                     1104
#define IDC_BUTTON_SAVEAS               1104
#define IDC_BUTTON3                     1105
#define IDC_BUTTON_CANCEL               1105
#define IDC_BUTTON_SAVE                 1106
#define IDC_BUTTON_DEL                  1107

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
