/*
 *  @file  : ..\ScdIcdCheckTool.h
 *  @author: user
 *  @date  : 2015-08-11 10:59:37.352
 *  @note  : Generated by SlxTemplates
 */

// ..\ScdIcdCheckTool.h : main header file for the SCDICDCHECKTOOL application
//

#if !defined(AFX_SCDICDCHECKTOOL_H__5D6429B4_C08D_4591_B09F_8215CC2D32CA__INCLUDED_)
#define AFX_SCDICDCHECKTOOL_H__5D6429B4_C08D_4591_B09F_8215CC2D32CA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

#ifndef __AFXWIN_H__
	#error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"		// main symbols

#include "Shared/SingleInst.h"
/////////////////////////////////////////////////////////////////////////////
// CScdIcdCheckToolApp:
// See ScdIcdCheckTool.cpp for the implementation of this class
//

class CScdIcdCheckToolApp : public CWinApp
{
private:
    ULONG_PTR	m_GdiplusToken;
    CSingleInst	m_siSingleInst;

public:
	CScdIcdCheckToolApp();

// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CScdIcdCheckToolApp)
	public:
	virtual BOOL InitInstance();
	//}}AFX_VIRTUAL

// Implementation

	//{{AFX_MSG(CScdIcdCheckToolApp)
		// NOTE - the ClassWizard will add and remove member functions here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
    virtual int ExitInstance();
};

extern CScdIcdCheckToolApp theApp;
/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SCDICDCHECKTOOL_H__5D6429B4_C08D_4591_B09F_8215CC2D32CA__INCLUDED_)
