/*
 *  @file  : stdafx.cpp
 *  @author: user
 *  @date  : 2015-08-11 10:59:37.352
 *  @note  : Generated by SlxTemplates
 */

// stdafx.cpp : source file that includes just the standard includes
//	ScdIcdCheckTool.pch will be the pre-compiled header
//	stdafx.obj will contain the pre-compiled type information

#include "stdafx.h"



